name: build
on: 
  push:
    paths:
      - '**.js'
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [16, 12, 14]
        exclude:
          - os: macos-latest
            node: 12
    
    steps:
      - uses: actions/checkout@v2
      - name: node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build --if-present
